name: Extract curl headers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  extract-curl-headers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install curl to download source
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Download curl source
        run: |
          sudo curl -LO https://github.com/curl/curl/releases/download/curl-8_13_0/curl-8.13.0.tar.gz
          sudo tar -xzf curl-8.13.0.tar.gz

      - name: Copy curl headers to include/
        run: |
          sudo mkdir -p include
          sudo cp -r curl-8.13.0/include/curl include/

      - name: Configure git for commit
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Added curl headers to include/" --allow-empty)

      - name: Pull latest changes
        run: |
          git pull origin main --rebase
          git push origin main

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
